print('Informe dois valores para serem calculados')
n1 = int(input('\nDigite o primeiro número '))
n2 = int(input('\nDigite o segundo número '))

s = (n1 + n2)
m = (n1 * n2)
d = (n1 / n2)
di = (n1 // n2)
rd = (n1 % n2)
e = (n1 ** n2)

print('\nSoma = {}'.format(s))
print('Multiplicação = {}'.format(m))
print('Divisão = {:.2f}'.format(d))
print('Divisão inteira = {}'.format(di))
print('Resto da divisão = {}'.format(rd))
print('Exponenciação = {}'.format(e))